<?php
$crumbs = $block->getCrumbs();
$currentPath = $block->getRequest()->getPathInfo();
$hideElements = strpos($currentPath, '/account/login') !== false || strpos($currentPath, '/account/create') !== false;
?>
<?php if (!$hideElements): ?>
  <?php if ($crumbs && is_array($crumbs)): ?>
    <div class="breadcrumbs">
      <div class="breadcrumbs-thumb"></div>
      <?php
      $lastCrumb = end($crumbs);
      ?>
      <h1><?= $block->escapeHtml($lastCrumb['label']) ?></h1>
      <ul class="items">
        <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
          <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
            <?php if ($crumbInfo['link']): ?>
              <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
            <?php else: ?>
              <?= $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
          </li>
        <?php endforeach; ?>
      </ul>
    </div>
  <?php endif; ?>
<?php endif; ?>